#!/bin/bash

echo "Create directories"

if [ "$#" -ne 3 ]; then
    echo "Usage: $0 <directory_prefix> <start_number> <end_number>"
    exit 1
fi

prefix=$1
start=$2
end=$3

for ((i = $start; i <= $end; i++)); do
    mkdir "$prefix$i"
done

echo "Directories created successfully."
